#!/usr/bin/python3

import pytest
import math

def test_main(USDC, DAI, WETH, accounts, NonfungiblePositionManager, UniswapV2Router02, CellarPoolShareContract, Contract):
    UniswapV2Router02.swapETHForExactTokens(10000 * 10 ** 18, [WETH, DAI], accounts[0], 2 ** 256 - 1, {"from": accounts[0], "value": 10 * 10 ** 18})
    DAI.approve(CellarPoolShareContract, 10000 * 10 ** 18, {"from": accounts[0]})
    cellarAddParams = [10000 * 10 ** 18, 7 * 10 ** 18, 0, 0, accounts[0], 2 ** 256 - 1]
    print("Contract balances")
    print("DAI")
    print(DAI.balanceOf(CellarPoolShareContract))
    print("ETH")
    print(CellarPoolShareContract.balance())
    print("WETH")
    print(WETH.balanceOf(CellarPoolShareContract))
    print("Account balances")
    print("DAI")
    print(DAI.balanceOf(accounts[0]))
    print("ETH")
    print(accounts[0].balance())
    print("WETH")
    print(WETH.balanceOf(accounts[0]))
    print("PoolShareBalance")
    bal = CellarPoolShareContract.balanceOf(accounts[0])
    print(bal)
    CellarPoolShareContract.addLiquidityEthForUniV3(cellarAddParams, {"from": accounts[0], "value": 7 * 10 ** 18})
    print("=====Added Liquidity=====")
    print("Contract balances")
    print("DAI")
    print(DAI.balanceOf(CellarPoolShareContract))
    print("ETH")
    print(CellarPoolShareContract.balance())
    print("WETH")
    print(WETH.balanceOf(CellarPoolShareContract))
    print("Account balances")
    print("DAI")
    print(DAI.balanceOf(accounts[0]))
    print("ETH")
    print(accounts[0].balance())
    print("WETH")
    print(WETH.balanceOf(accounts[0]))
    print("PoolShareBalance")
    bal = CellarPoolShareContract.balanceOf(accounts[0])
    print(bal)
    cellarRebalanceParams = [[0, -30000, -60000, 3], [0, -60000, -90000, 1], [0, -90000, -120000, 2]]
    CellarPoolShareContract.rebalance(cellarRebalanceParams)
    print("=====Rebalanced=====")
    print("Contract balances")
    print("DAI")
    print(DAI.balanceOf(CellarPoolShareContract))
    print("ETH")
    print(CellarPoolShareContract.balance())
    print("WETH")
    print(WETH.balanceOf(CellarPoolShareContract))
    print("Account balances")
    print("DAI")
    print(DAI.balanceOf(accounts[0]))
    print("ETH")
    print(accounts[0].balance())
    print("WETH")
    print(WETH.balanceOf(accounts[0]))
    print("PoolShareBalance")
    bal = CellarPoolShareContract.balanceOf(accounts[0])
    print(bal)
    cellarRemoveParams = [bal // 2, 0, 0, accounts[0], 2 ** 256 - 1]
    CellarPoolShareContract.removeLiquidityEthFromUniV3(cellarRemoveParams, {"from": accounts[0]})
    print("=====RemovedHalf=====")
    print("Contract balances")
    print("DAI")
    print(DAI.balanceOf(CellarPoolShareContract))
    print("ETH")
    print(CellarPoolShareContract.balance())
    print("WETH")
    print(WETH.balanceOf(CellarPoolShareContract))
    print("Account balances")
    print("DAI")
    print(DAI.balanceOf(accounts[0]))
    print("ETH")
    print(accounts[0].balance())
    print("WETH")
    print(WETH.balanceOf(accounts[0]))
    print("PoolShareBalance")
    bal = CellarPoolShareContract.balanceOf(accounts[0])
    print(bal)
    CellarPoolShareContract.removeLiquidityEthFromUniV3(cellarRemoveParams, {"from": accounts[0]})
    print("=====RemovedAll=====")
    print("Contract balances")
    print("DAI")
    print(DAI.balanceOf(CellarPoolShareContract))
    print("ETH")
    print(CellarPoolShareContract.balance())
    print("WETH")
    print(WETH.balanceOf(CellarPoolShareContract))
    print("Account balances")
    print("DAI")
    print(DAI.balanceOf(accounts[0]))
    print("ETH")
    print(accounts[0].balance())
    print("WETH")
    print(WETH.balanceOf(accounts[0]))
    print("PoolShareBalance")
    bal = CellarPoolShareContract.balanceOf(accounts[0])
    print(bal)