// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.21;

contract PositionIds {
    uint32 public constant ERC20_USDC_POSITION = 1;
    uint32 public constant ERC20_USDCE_POSITION = 2;
    uint32 public constant ERC20_DAI_POSITION = 3;
    uint32 public constant ERC20_USDT_POSITION = 4;
    uint32 public constant ERC20_LUSD_POSITION = 5;
    uint32 public constant ERC20_FRAX_POSITION = 6;
    uint32 public constant ERC20_WETH_POSITION = 7;
    uint32 public constant ERC20_WSTETH_POSITION = 8;
    uint32 public constant ERC20_RETH_POSITION = 9;
    uint32 public constant AAVE_V3_LOW_HF_A_USDC_POSITION = 10;
    uint32 public constant AAVE_V3_LOW_HF_A_USDCE_POSITION = 11;
    uint32 public constant AAVE_V3_LOW_HF_A_DAI_POSITION = 12;
    uint32 public constant AAVE_V3_LOW_HF_A_USDT_POSITION = 13;
    uint32 public constant AAVE_V3_LOW_HF_A_LUSD_POSITION = 14;
    uint32 public constant AAVE_V3_LOW_HF_A_FRAX_POSITION = 15;
    uint32 public constant AAVE_V3_LOW_HF_A_WETH_POSITION = 16;
    uint32 public constant AAVE_V3_LOW_HF_A_WSTETH_POSITION = 17;
    uint32 public constant AAVE_V3_LOW_HF_A_RETH_POSITION = 18;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_USDC_POSITION = 19;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_USDCE_POSITION = 20;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_DAI_POSITION = 21;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_USDT_POSITION = 22;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_LUSD_POSITION = 23;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_FRAX_POSITION = 24;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_WETH_POSITION = 25;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_WSTETH_POSITION = 26;
    uint32 public constant AAVE_V3_LOW_HF_DEBT_RETH_POSITION = 27;
    uint32 public constant UNISWAP_V3_USDC_USDCE_POSITION = 28;
    uint32 public constant UNISWAP_V3_USDC_DAI_POSITION = 29;
    uint32 public constant UNISWAP_V3_USDC_USDT_POSITION = 30;
    uint32 public constant UNISWAP_V3_USDC_LUSD_POSITION = 31;
    uint32 public constant UNISWAP_V3_USDC_FRAX_POSITION = 32;
    uint32 public constant UNISWAP_V3_USDCE_DAI_POSITION = 33;
    uint32 public constant UNISWAP_V3_USDCE_USDT_POSITION = 34;
    uint32 public constant UNISWAP_V3_USDCE_LUSD_POSITION = 35;
    uint32 public constant UNISWAP_V3_USDCE_FRAX_POSITION = 36;
    uint32 public constant UNISWAP_V3_DAI_USDT_POSITION = 37;
    uint32 public constant UNISWAP_V3_DAI_LUSD_POSITION = 38;
    uint32 public constant UNISWAP_V3_DAI_FRAX_POSITION = 39;
    uint32 public constant UNISWAP_V3_USDT_LUSD_POSITION = 40;
    uint32 public constant UNISWAP_V3_USDT_FRAX_POSITION = 41;
    uint32 public constant UNISWAP_V3_LUSD_FRAX_POSITION = 42;
    uint32 public constant UNISWAP_V3_WETH_WSTETH_POSITION = 43;
    uint32 public constant UNISWAP_V3_WETH_RETH_POSITION = 44;
    uint32 public constant UNISWAP_V3_WSTETH_RETH_POSITION = 45;
    uint32 public constant COMPOUND_V3_SUPPLY_USDC_POSITION = 46;
    uint32 public constant COMPOUND_V3_SUPPLY_USDCE_POSITION = 47;
}
